apiVersion: v1
kind: Template
metadata:
  name: cd-pipeline
  annotations:
    openshift.io/display-name: CD Pipeline
    iconClass: fa fa-code
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}-cd-pipeline
  spec:
    source:
      type: Git
      git:
        uri: ${GIT_REPO}
        ref: ${GIT_BRANCH}
      contextDir: ${OPENSHIFT_DIR}/pipelines/cd
      sourceSecret:
        name: pipeline-ocp
    strategy:
      jenkinsPipelineStrategy:
        env:
        - name: APP_NAME
          value: ${APP_NAME}
        - name: APP_GIT_REPO
          value: ${APP_GIT_REPO}
        - name: APP_GIT_BRANCH
          value: ${APP_GIT_BRANCH}
        - name: APP_GIT_SECRET
          value: ${APP_GIT_SECRET}
        - name: OPENSHIFT_DIR
          value: ${OPENSHIFT_DIR}
        - name: PROJECT_NAME
          value: ${PROJECT_NAME}
        - name: APP_TEMPLATE
          value: ${APP_NAME}/openshift/template.yaml
        - name: APP_TEMPLATE_PARAMETERS_PROD
          value: ${APP_NAME}/openshift/environments/${PARAM_ENV}/templateParameters.txt
        - name: APP_REPLACE_CONFIG_PROD
          value: ${APP_NAME}/openshift/environments/${PARAM_ENV}/replaceConfig.yaml
        - name: APP_DEPLOYMENT_PATCH_PROD
          value: ${APP_NAME}/openshift/environments/${PARAM_ENV}/deploymentPatch.yaml
        - name: APP_CONFIGMAP_DIR
          value: ${APP_NAME}/openshift/environments/${PARAM_ENV}/cm/
        - name: APP_CONFIGMAP_DIR_LOCAL
          value: ${APP_NAME}/openshift/environments/${PARAM_ENV}/${APP_CM_LOCAL}/
        - name: APP_CONFIGMAP_DIR_REMOTO
          value: ${APP_NAME}/openshift/environments/${PARAM_ENV}/${APP_CM_REMOTO}/
        - name: IMAGE_REPO_URL
          value: ${IMAGE_REPO_URL}
        - name: IMAGE_NAME
          value: ${IMAGE_NAME}
        - name: JENKINS_PROJECT_NAME
          value: ${JENKINS_PROJECT_NAME}
        - name: SRC_REGISTRY_URL
          value: ${SRC_REGISTRY_URL}
        - name: SRC_REGISTRY_CREDENTIALS
          value: ${SRC_REGISTRY_CREDENTIALS}
        - name: SRC_REGISTRY_PROJECT
          value: ${SRC_REGISTRY_PROJECT}
        - name: DST_REGISTRY_URL
          value: ${DST_REGISTRY_URL}
        - name: DST_REGISTRY_CREDENTIALS
          value: ${DST_REGISTRY_CREDENTIALS}
        - name: DST_REGISTRY_PROJECT
          value: ${DST_REGISTRY_PROJECT}
        - name: LOCAL_CLUSTER_URL
          value: ${LOCAL_CLUSTER_URL}
        - name: LOCAL_CLUSTER_CREDENTIALS
          value: ${LOCAL_CLUSTER_CREDENTIALS}
        - name: REMOTO_CLUSTER_URL
          value: ${REMOTO_CLUSTER_URL}
        - name: REMOTO_CLUSTER_CREDENTIALS
          value: ${REMOTO_CLUSTER_CREDENTIALS}

        jenkinsfilePath: Jenkinsfile
      type: JenkinsPipeline
    triggers:
      - generic:
          allowEnv: true
          secret: ${WEBHOOK_SECRET}
        type: Generic
parameters:
- description: Proyecto destino
  displayName: Proyecto destino
  name: PROJECT_NAME
  required: true
- description: Environment a desplegar
  displayName: Environment a desplegar
  name: PARAM_ENV
  required: true
- description: Application Name
  displayName: Application Name
  name: APP_NAME
  required: true
- description: Git Repository
  displayName: Git Repository
  name: APP_GIT_REPO
  required: true
- description: Git Branch
  displayName: Git Branch
  name: APP_GIT_BRANCH
  required: true
- description: APP Git Secret
  displayName: APP Git Secret
  name: APP_GIT_SECRET
  required: true
- description: APP Directorio de configuracion cluster remoto
  displayName: APP Directorio de configuracion cluster remoto
  name: APP_CM_REMOTO
  required: true
- description: APP Directorio de configuracion cluster local
  displayName: APP Directorio de configuracion cluster local
  name: APP_CM_LOCAL
  required: true
- description: Git Repository
  displayName: Git Repository
  name: GIT_REPO
  required: true
- description: Git Branch
  displayName: Git Branch
  name: GIT_BRANCH
  value: master
  required: true
- description: OpenShift Directory
  displayName: OpenShift Directory
  name: OPENSHIFT_DIR
  value: ./
  required: true
- description: Nombre de la imagen como se encuentra en el Repo Nexus
  displayName: Image name
  name: IMAGE_NAME
  required: true
- name: JENKINS_PROJECT_NAME
  value: custom-cicd
  description: Nombre de la imagen como se encuentra en el Repo Nexus
  displayName: Image name
  required: false
- name: SRC_REGISTRY_URL
  description: Nombre de la imagen como se encuentra en el Repo Nexus
  displayName: Image name
  required: true
- name: SRC_REGISTRY_CREDENTIALS
  description: Nombre de la imagen como se encuentra en el Repo Nexus
  displayName: Image name
  required: true
- name: SRC_REGISTRY_PROJECT
  description: Nombre de la imagen como se encuentra en el Repo Nexus
  displayName: Image name
  required: true
- name: DST_REGISTRY_URL
  description: Nombre de la imagen como se encuentra en el Repo Nexus
  displayName: Image name
  required: true
- name: DST_REGISTRY_CREDENTIALS
  description: Nombre de la imagen como se encuentra en el Repo Nexus
  displayName: Image name
  required: true
- name: DST_REGISTRY_PROJECT
  description: Nombre de la imagen como se encuentra en el Repo Nexus
  displayName: Image name
  required: true
- name: LOCAL_CLUSTER_URL
  description: Nombre de la imagen como se encuentra en el Repo Nexus
  displayName: Image name
  required: true
- name: LOCAL_CLUSTER_CREDENTIALS
  description: Nombre de la imagen como se encuentra en el Repo Nexus
  displayName: Image name
  required: true
- name: REMOTO_CLUSTER_URL
  description: Nombre de la imagen como se encuentra en el Repo Nexus
  displayName: Image name
  required: true
- name: REMOTO_CLUSTER_CREDENTIALS
  description: Nombre de la imagen como se encuentra en el Repo Nexus
  displayName: Image name
  required: true
- description: Webhook Secret
  displayName: Webhook Secret
  name: WEBHOOK_SECRET
  generate: expression
  from: "[a-zA-Z0-9]{40}"
