apiVersion: v1
kind: Template
metadata:
  name: ci-pipeline
  annotations:
    openshift.io/display-name: CI Pipeline
    iconClass: fa fa-code
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}-ci-pipeline
  spec:
    source:
      git:
        uri: ${GIT_REPO}
        ref: ${GIT_BRANCH}
      contextDir: pipelines/ci
      sourceSecret:
        name: git-access
      type: Git
    strategy:
      jenkinsPipelineStrategy:
        env:
          - name: APP_NAME
            value: ${APP_NAME}
          - name: APP_GIT_REPO
            value: ${APP_GIT_REPO}
          - name: APP_GIT_BRANCH
            value: ${APP_GIT_BRANCH}
          - name: DEV_PROJECT
            value: ${PROJECT_NAME}
        jenkinsfilePath: Jenkinsfile
      type: JenkinsPipeline
    triggers:
      - generic:
          allowEnv: true
          secret: ${WEBHOOK_SECRET}
        type: Generic
parameters:
- description: Proyecto destino
  displayName: Proyecto destino
  name: PROJECT_NAME
  required: true
- description: Application Name
  displayName: Application Name
  name: APP_NAME
  required: true
- description: Git Repository
  displayName: Git Repository
  name: APP_GIT_REPO
  required: true
- description: Git Branch
  displayName: Git Branch
  name: APP_GIT_BRANCH
  required: true
- description: Git Repository
  displayName: Git Repository
  name: GIT_REPO
  required: true
- description: Git Branch
  displayName: Git Branch
  name: GIT_BRANCH
  required: true
- description: Webhook Secret
  displayName: Webhook Secret
  name: WEBHOOK_SECRET
  generate: expression
  from: "[a-zA-Z0-9]{40}"
