apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: add-jenkins-edit
  annotations:
    openshift.io/display-name: Grant jenkins edit permissions to a project
    iconClass: fa fa-puzzle-piece
objects:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: jenkins-edit
    namespace: ${PROJECT_NAME}
  subjects:
    - kind: ServiceAccount
      name: jenkins
      namespace: cicd
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: edit
parameters:
- description: Proyecto destino
  displayName: Proyecto destino
  name: PROJECT_NAME
  required: true
