kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins-group-reader
subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: jenkins-project
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: group-reader
