apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: group-reader
rules:
- apiGroups:
  - user.openshift.io
  resources:
  - groups
  - identities
  - useridentitymappings
  - users
  verbs:
  - get
  - list
  - watch
